In [1]:
import pandas as pd
import numpy as np
from math import log2

path = "/home/colombelli/Documents/datasets/assembler/"
luad = "luad/LUAD__gene.normalized_RNAseq__tissueTypeAll__20200822175257.txt"
luad_microarr = "luad/LUAD__gene_Array__tissueTypeAll__20201020150206.txt"
prad = "prad/PRAD__gene.normalized_RNAseq__tissueTypeAll__20200822180034.txt"
thca = "thca/THCA__gene.normalized_RNAseq__tissueTypeAll__20200822180826.txt"

In [6]:
def set_new_cols(data):
    print("Getting gene symbols")
    new_cols = []
    count_no_gene_sym = 0

    for gene in data.columns:
        symbol = gene.split('|')[0]
        if symbol == '?':
            new_cols.append(gene.split('|')[1])
            count_no_gene_sym +=1
        else:
            new_cols.append(symbol)
            
    print("Genes without symbol:", count_no_gene_sym)
    data.columns = new_cols
    return


def log_transform_data(data):
    print("Log transforming")
    df = (data+1).applymap(log2)
    return df


def set_class_column(data):
    print("Getting classes")
    classes = []

    for barcode in data.index:
        sample_type = int(barcode.split('-')[3][0:-1])
        if sample_type > 9 and sample_type < 20:    # Codes within [10, 19] are normal sample types
            classes.append(0)
        elif sample_type > 0 and sample_type < 10:  # Codes within [1, 9] are tumoral sample types
            classes.append(1)
        else:
            print("Control sample type found for barcode:", barcode)
            classes.append(0)

        if sample_type != 1 and sample_type != 6 and sample_type != 11:
            print("Unexpected sample type found for barcode:", barcode)
        
        
    np_cls = np.array(classes)
    print("Classes info:\n", np.unique(np_cls, return_counts=True))
    data['class'] = classes
    return


def process_dataset(file_path, log=True):
    
    print("Loading dataset...")
    df = pd.read_csv(file_path, sep="\t")
    df = df.T
    df.columns = df.iloc[0]
    df = df.drop(df.index[0])
    
    set_new_cols(df)
    if log:
        df = log_transform_data(df)
    set_class_column(df)
    return df

In [3]:
def save_processed_df(df, path_and_name):
    print("Saving dataset...")
    df.to_csv(path_and_name)
    return pd.read_csv(path_and_name, index_col=0)

In [19]:
df = process_dataset(path+luad)
save_processed_df(df, path+"luad/luad_log2.csv")

Loading dataset...
Getting gene symbols
Genes without symbol: 29
Log transforming
Getting classes
Unexpected sample type found for barcode: TCGA-50-5066-02A-11R-2090-07
Unexpected sample type found for barcode: TCGA-50-5946-02A-11R-2090-07
Classes info:
 (array([0, 1]), array([ 59, 517]))
Saving dataset...


100130426  100133144  100134869     10357  \
TCGA-05-4244-01A-01R-1107-07        0.0   3.460913   3.618474  5.661048   
TCGA-05-4249-01A-01R-1107-07        0.0   3.034867   3.748848  6.515884   
TCGA-05-4250-01A-01R-1107-07        0.0   3.043572   2.811142  5.659257   
TCGA-05-4382-01A-01R-1206-07        0.0   3.624230   3.099968  6.389400   
TCGA-05-4384-01A-01R-1755-07        0.0   2.079088   2.168064  6.200361   
...                                 ...        ...        ...       ...   
TCGA-NJ-A55O-01A-11R-A262-07        0.0   4.046081   4.584193  6.660876   
TCGA-NJ-A55R-01A-11R-A262-07        0.0   3.235650   3.501133  6.242622   
TCGA-NJ-A7XG-01A-12R-A39D-07        0.0   5.458963   6.359535  6.432483   
TCGA-O1-A52J-01A-11R-A262-07        0.0   3.915148   4.654859  5.957422   
TCGA-S2-AA1A-01A-12R-A39D-07        0.0   4.428531   3.314697  6.284042   

                                  10431  136542    155060     26823    280660  \
TCGA-05-4244-01A-01R-1107-07   9.731217     0.0  8.435590  1.033652  0.000000   
TCGA-05-4249-01A-01R-1107-07   9.853334     0.0  7.191824  1.383939  0.000000   
TCGA-05-4250-01A-01R-1107-07  10.156940     0.0  5.720508  0.000000  0.000000   
TCGA-05-4382-01A-01R-1206-07   9.658520     0.0  7.913022  0.564232  0.309525   
TCGA-05-4384-01A-01R-1755-07   9.137001     0.0  8.104768  0.687867  0.000000   
...                                 ...     ...       ...       ...       ...   
TCGA-NJ-A55O-01A-11R-A262-07   9.773105     0.0  8.006332  1.115633  0.000000   
TCGA-NJ-A55R-01A-11R-A262-07   9.584483     0.0  8.536352  0.783163  0.000000   
TCGA-NJ-A7XG-01A-12R-A39D-07   9.406701     0.0  8.391223  0.000000  0.000000   
TCGA-O1-A52J-01A-11R-A262-07  10.152691     0.0  7.424699  1.952632  0.000000   
TCGA-S2-AA1A-01A-12R-A39D-07   9.145763     0.0  8.563740  0.727006  0.000000   

                              317712  ...      ZWINT      ZXDA      ZXDB  \
TCGA-05-4244-01A-01R-1107-07     0.0  ...   9.018678  5.350285  8.197321   
TCGA-05-4249-01A-01R-1107-07     0.0  ...   8.172465  5.980428  8.950001   
TCGA-05-4250-01A-01R-1107-07     0.0  ...  10.033199  5.931168  8.517334   
TCGA-05-4382-01A-01R-1206-07     0.0  ...   9.558593  5.373036  8.441914   
TCGA-05-4384-01A-01R-1755-07     0.0  ...   7.275567  6.340285  9.140128   
...                              ...  ...        ...       ...       ...   
TCGA-NJ-A55O-01A-11R-A262-07     0.0  ...   8.530321  5.386814  8.366562   
TCGA-NJ-A55R-01A-11R-A262-07     0.0  ...   8.810213  5.692087  8.552138   
TCGA-NJ-A7XG-01A-12R-A39D-07     0.0  ...   7.424646  4.165373  7.409182   
TCGA-O1-A52J-01A-11R-A262-07     0.0  ...   8.529122  7.101856  9.138731   
TCGA-S2-AA1A-01A-12R-A39D-07     0.0  ...   7.044821  5.937297  8.512893   

                                   ZXDC    ZYG11A     ZYG11B        ZYX  \
TCGA-05-4244-01A-01R-1107-07   9.907260  0.763921  10.088859  11.471139   
TCGA-05-4249-01A-01R-1107-07  10.204971  4.411650   9.622978  11.199826   
TCGA-05-4250-01A-01R-1107-07   9.722642  4.782796   8.895339  12.408981   
TCGA-05-4382-01A-01R-1206-07   9.888267  6.041142   9.828389  12.725186   
TCGA-05-4384-01A-01R-1755-07  10.368188  3.160501   9.607078  11.706702   
...                                 ...       ...        ...        ...   
TCGA-NJ-A55O-01A-11R-A262-07  10.114199  4.209680   9.506548  12.031540   
TCGA-NJ-A55R-01A-11R-A262-07  10.537639  5.744756   9.567679  11.588149   
TCGA-NJ-A7XG-01A-12R-A39D-07  10.259693  3.469157   9.057056  10.963035   
TCGA-O1-A52J-01A-11R-A262-07  10.341686  0.564134   9.613415  12.130652   
TCGA-S2-AA1A-01A-12R-A39D-07  10.838901  2.916859   9.285612  12.384620   

                                  ZZEF1      ZZZ3  class  
TCGA-05-4244-01A-01R-1107-07   9.768648  9.170597      1  
TCGA-05-4249-01A-01R-1107-07  10.153700  9.433116      1  
TCGA-05-4250-01A-01R-1107-07  10.194168  9.060342      1  
TCGA-05-4382-01A-01R-1206-07  10.192589  9.376841      1  
TCGA-05-4384-01A-01R-1755-07  10.763482  9.5003

In [13]:
df = process_dataset(path+luad_microarr, log=False)
df

#df = pd.read_csv(path+"/BRCA__gene_Array__tissueTypeAll__20201020151509.txt", sep="\t")
#df = df.T
#df

Loading dataset...
Getting gene symbols
Genes without symbol: 0
Getting classes
Classes info:
 (array([1]), array([32]))


15E1.2     2'-PDE     7A5       A1BG     A2BP1  \
TCGA-05-4244-01A-01R-1107-07  -0.3095 -0.0786429   1.292   -2.04983    -1.426   
TCGA-05-4249-01A-01R-1107-07   0.7035   -0.06325  3.0055    -0.2454  -1.52133   
TCGA-05-4250-01A-01R-1107-07   1.8615  -0.088125  1.5545    1.09117    -1.102   
TCGA-35-3615-01A-01R-0946-07   -0.811      -0.24   1.502  -0.499167    -1.295   
TCGA-35-4122-01A-01R-1107-07   -0.581    -0.0205   3.682   0.992333   -1.8325   
TCGA-35-4123-01A-01R-1107-07 -0.33425   0.104813   3.518    1.15333 -0.968167   
TCGA-44-2655-01A-01R-0946-07   -0.622   0.502062   3.069  -0.245167  -1.19583   
TCGA-44-2656-01A-02R-0946-07  0.03825  0.0280625    2.68    -0.5105    -2.182   
TCGA-44-2657-01A-01R-1107-07  -1.3545  -0.147625   2.983   0.860833 -0.900333   
TCGA-44-2659-01A-01R-0946-07  -1.2365    -0.1745  3.3355     -0.226    -1.141   
TCGA-44-2661-01A-01R-1107-07 -1.61775   0.096375    3.35      0.366   -1.1125   
TCGA-44-2662-01A-01R-0946-07   0.4105   0.278125   2.954   0.137167  -2.17667   
TCGA-44-2665-01A-01R-0946-07 -1.11975   -0.07575  2.9955 -0.0336667  -1.03567   
TCGA-44-2666-01A-01R-0946-07 -0.94225   0.153438  1.9855     -1.711   3.30933   
TCGA-44-2668-01A-01R-0946-07 -0.20375  0.0218125  2.2145  -0.492167  -1.63517   
TCGA-44-3398-01A-01R-1107-07   1.4085  -0.580688  2.3605    1.41367  -2.37967   
TCGA-44-3918-01A-01R-1107-07    1.338   0.030875  0.2215      1.141   -2.1565   
TCGA-44-3919-01A-02R-1107-07   -0.319  -0.588187  3.0665      0.514    0.7555   
TCGA-44-4112-01A-01R-1107-07    -0.78    0.13625   3.897   0.489833   -1.3845   
TCGA-55-1592-01A-01R-0946-07 -1.32175  0.0218125  0.8225     0.1985  -2.20717   
TCGA-55-1594-01A-01R-0946-07    0.918   0.104438   0.857  -0.865833   -1.9975   
TCGA-55-1595-01A-01R-0946-07 -0.14575   0.175625  1.8275   0.411667    -1.542   
TCGA-55-1596-01A-01R-0946-07  0.86925   0.125438   2.868    -1.7005  -2.16467   
TCGA-64-1676-01A-01R-0946-07    0.567  -0.628938  -0.072      1.352  -1.62817   
TCGA-64-1677-01A-01R-0946-07      1.5   0.104125  2.8435      -0.24   -0.9515   
TCGA-64-1678-01A-01R-0946-07   1.3415  -0.206625  1.4325    1.04767  -1.13433   
TCGA-64-1680-01A-02R-0946-07  -0.4735   0.000375   3.138    1.26667  -1.64017   
TCGA-67-3770-01A-01R-0946-07   -0.103  -0.360125  3.1215    1.60683   -1.5725   
TCGA-67-3771-01A-01R-0946-07 -0.76775   0.041125   0.927    1.07383 -0.250167   
TCGA-67-3772-01A-01R-0946-07 -0.56575  -0.730437   4.732   0.862333   1.85983   
TCGA-67-3773-01A-01R-0946-07 -1.09725  -0.276438  1.0605  -0.380667  -1.29383   
TCGA-67-3774-01A-01R-0946-07 -1.48675   0.323188  1.0045  -0.972833   -1.0925   

                                  A2M   A2ML1  A3GALT2     A4GALT   A4GNT  \
TCGA-05-4244-01A-01R-1107-07  0.08975   0.262  1.60533    -0.7175     NaN   
TCGA-05-4249-01A-01R-1107-07    0.731   0.441 -0.19575   0.604667    0.31   
TCGA-05-4250-01A-01R-1107-07   -0.097  1.3325  0.29675      0.133   0.259   
TCGA-35-3615-01A-01R-0946-07  -0.2985  1.1495    0.625  -0.548333  0.5365   
TCGA-35-4122-01A-01R-1107-07  0.97425  0.7165  0.35025      0.222  0.5025   
TCGA-35-4123-01A-01R-1107-07  0.50675  0.6385  0.28925  0.0703333   0.333   
TCGA-44-2655-01A-01R-0946-07  2.11075   0.857   0.6195  -0.142833 -0.4815   
TCGA-44-2656-01A-02R-0946-07    1.878   0.777  0.26225  -0.259667   0.862   
TCGA-44-2657-01A-01R-1107-07   2.5675   1.079  0.10925     0.0725   0.458   
TCGA-44-2659-01A-01R-0946-07    2.229   1.234    0.061    -0.4025   0.453   
TCGA-44-2661-01A-01R-1107-07    1.575   0.551   0.4485    1.17183 -0.2925   
TCGA-44-2662-01A-01R-0946-07  0.08125   0.483 -0.01925    -0.5115   1.524   
TCGA-44-2665-01A-01R-0946-07  0.29075  0.2715 -0.36125     0.2215  0.1935   
TCGA-44-2666-01A-01R-0946-07   2.6605   0.571   0.2005   0.520833   0.597   
TCGA-44-2668-01A-01R-0946-07   0.0675  0.6645     0.46    1.54983  1.4135   
TCGA-44-3398-01A-01R-1107-07 -0.05475   1.318   0.6285   0.300833 -0.3475   
TCGA-44-3918-01A-01R-1107-07   -0.191   1.039 -0

In [20]:
df = process_dataset(path+prad)
save_processed_df(df, path+"prad/prad_log2.csv")

Loading dataset...
Getting gene symbols
Genes without symbol: 29
Log transforming
Getting classes
Classes info:
 (array([0, 1]), array([ 52, 498]))
Saving dataset...


100130426  100133144  100134869     10357  \
TCGA-2A-A8VL-01A-21R-A37L-07    0.00000   4.443063   4.197960  6.355992   
TCGA-2A-A8VO-01A-11R-A37L-07    0.00000   4.344871   3.898257  5.979012   
TCGA-2A-A8VT-01A-11R-A37L-07    0.00000   5.640563   5.911744  6.576262   
TCGA-2A-A8VV-01A-11R-A37L-07    0.00000   4.506799   4.120004  6.770158   
TCGA-2A-A8VX-01A-11R-A37L-07    0.00000   1.982765   3.268404  6.613591   
...                                 ...        ...        ...       ...   
TCGA-ZG-A9M4-01A-11R-A41O-07    0.53037   4.356968   4.788816  6.970637   
TCGA-ZG-A9MC-01A-31R-A41O-07    0.00000   3.821516   3.990038  6.734920   
TCGA-ZG-A9N3-01A-11R-A41O-07    0.00000   2.889532   2.989956  6.999465   
TCGA-ZG-A9ND-01A-11R-A41O-07    0.00000   3.523524   4.608378  6.033258   
TCGA-ZG-A9NI-01A-11R-A41O-07    0.00000   3.901118   3.018207  6.322410   

                                  10431  136542     155060    26823   280660  \
TCGA-2A-A8VL-01A-21R-A37L-07  10.357574     0.0   8.304415  0.00000  0.00000   
TCGA-2A-A8VO-01A-11R-A37L-07   9.756570     0.0   8.566700  0.00000  0.00000   
TCGA-2A-A8VT-01A-11R-A37L-07   9.189134     0.0   9.513292  1.07238  0.00000   
TCGA-2A-A8VV-01A-11R-A37L-07   9.845014     0.0   7.896056  0.00000  0.00000   
TCGA-2A-A8VX-01A-11R-A37L-07   9.703645     0.0   8.346399  0.00000  0.00000   
...                                 ...     ...        ...      ...      ...   
TCGA-ZG-A9M4-01A-11R-A41O-07   8.821826     0.0  10.983346  0.00000  0.00000   
TCGA-ZG-A9MC-01A-31R-A41O-07   8.998620     0.0   8.032105  0.00000  0.00000   
TCGA-ZG-A9N3-01A-11R-A41O-07  10.571173     0.0   7.422318  0.00000  1.01956   
TCGA-ZG-A9ND-01A-11R-A41O-07  10.214231     0.0   8.016795  0.00000  0.00000   
TCGA-ZG-A9NI-01A-11R-A41O-07  10.360413     0.0   6.894623  0.00000  0.00000   

                              317712  ...      ZWINT      ZXDA      ZXDB  \
TCGA-2A-A8VL-01A-21R-A37L-07     0.0  ...   6.619447  5.611432  8.156048   
TCGA-2A-A8VO-01A-11R-A37L-07     0.0  ...   7.892424  5.421937  8.586790   
TCGA-2A-A8VT-01A-11R-A37L-07     0.0  ...   6.934558  6.835865  9.228571   
TCGA-2A-A8VV-01A-11R-A37L-07     0.0  ...   7.203301  5.514473  8.721872   
TCGA-2A-A8VX-01A-11R-A37L-07     0.0  ...   8.289457  4.654458  8.490792   
...                              ...  ...        ...       ...       ...   
TCGA-ZG-A9M4-01A-11R-A41O-07     0.0  ...   7.285975  6.079766  8.649915   
TCGA-ZG-A9MC-01A-31R-A41O-07     0.0  ...   6.715675  6.067512  8.857866   
TCGA-ZG-A9N3-01A-11R-A41O-07     0.0  ...  10.968822  5.247259  8.600984   
TCGA-ZG-A9ND-01A-11R-A41O-07     0.0  ...   7.727670  5.543836  8.327548   
TCGA-ZG-A9NI-01A-11R-A41O-07     0.0  ...   8.756073  5.526363  8.166503   

                                   ZXDC    ZYG11A     ZYG11B        ZYX  \
TCGA-2A-A8VL-01A-21R-A37L-07  10.106487  5.289281   9.436857  11.170432   
TCGA-2A-A8VO-01A-11R-A37L-07   9.827936  7.396474   9.564797  11.405844   
TCGA-2A-A8VT-01A-11R-A37L-07  10.755366  5.507328  10.218937  10.584548   
TCGA-2A-A8VV-01A-11R-A37L-07   9.990273  6.032943   9.261573  11.579402   
TCGA-2A-A8VX-01A-11R-A37L-07   9.959399  7.364122   9.470459  11.150269   
...                                 ...       ...        ...        ...   
TCGA-ZG-A9M4-01A-11R-A41O-07  10.310744  6.595229   9.337349  10.516591   
TCGA-ZG-A9MC-01A-31R-A41O-07  10.538661  6.249352   9.975857  12.065681   
TCGA-ZG-A9N3-01A-11R-A41O-07   9.878005  7.987055   9.978384  11.302684   
TCGA-ZG-A9ND-01A-11R-A41O-07  10.107021  7.164772   9.654848  10.508092   
TCGA-ZG-A9NI-01A-11R-A41O-07  10.230176  6.838889   9.477072  12.257227   

                                  ZZEF1       ZZZ3  class  
TCGA-2A-A8VL-01A-21R-A37L-07  10.540779   8.983419      1  
TCGA-2A-A8VO-01A-11R-A37L-07   9.739847   9.325745      1  
TCGA-2A-A8VT-01A-11R-A37L-07  11.023928  10.424722      1  
TCGA-2A-A8VV-01A-11R-A37L-07  10.009504  10.036262      1  
TCGA-2A-A8VX-01A-11R-A37L-07   9.711469   9.557922    

In [21]:
df = process_dataset(path+thca)
save_processed_df(df, path+"thca/thca_log2.csv")

Loading dataset...
Getting gene symbols
Genes without symbol: 29
Log transforming
Getting classes
Classes info:
 (array([0, 1]), array([ 59, 513]))
Saving dataset...


100130426  100133144  100134869     10357  \
TCGA-4C-A93U-01A-11R-A39I-07        0.0   1.552082   0.000000  7.061192   
TCGA-BJ-A0YZ-01A-11R-A10U-07        0.0   3.537060   1.529421  7.135796   
TCGA-BJ-A0Z0-01A-11R-A10U-07        0.0   2.633152   1.884676  7.509491   
TCGA-BJ-A0Z2-01A-11R-A10U-07        0.0   3.503769   3.470758  7.677577   
TCGA-BJ-A0Z3-01A-11R-A13Y-07        0.0   1.705845   2.535804  7.395265   
...                                 ...        ...        ...       ...   
TCGA-MK-A4N6-01A-11R-A250-07        0.0   2.283151   2.903308  6.870865   
TCGA-MK-A4N7-01A-11R-A250-07        0.0   2.710217   3.237288  7.377259   
TCGA-MK-A4N9-01A-11R-A250-07        0.0   2.498557   3.967113  7.111762   
TCGA-MK-A84Z-01A-11R-A39I-07        0.0   0.000000   2.953004  7.048441   
TCGA-QD-A8IV-01A-11R-A39I-07        0.0   1.610417   3.040437  6.956948   

                                  10431  136542    155060     26823    280660  \
TCGA-4C-A93U-01A-11R-A39I-07   9.301386     0.0  8.240550  0.568616  0.000000   
TCGA-BJ-A0YZ-01A-11R-A10U-07  10.774049     0.0  5.535984  0.502331  0.000000   
TCGA-BJ-A0Z0-01A-11R-A10U-07   9.823909     0.0  7.053899  0.480058  0.000000   
TCGA-BJ-A0Z2-01A-11R-A10U-07   9.852725     0.0  7.962813  0.963622  0.000000   
TCGA-BJ-A0Z3-01A-11R-A13Y-07   9.635258     0.0  7.086891  0.606916  1.032877   
...                                 ...     ...       ...       ...       ...   
TCGA-MK-A4N6-01A-11R-A250-07   9.459332     0.0  6.728208  0.468114  0.000000   
TCGA-MK-A4N7-01A-11R-A250-07   9.593059     0.0  7.820870  0.382723  0.382723   
TCGA-MK-A4N9-01A-11R-A250-07   9.655508     0.0  8.506455  0.514703  1.192825   
TCGA-MK-A84Z-01A-11R-A39I-07  10.062860     0.0  8.504144  1.026800  0.000000   
TCGA-QD-A8IV-01A-11R-A39I-07   9.476011     0.0  8.219090  1.454229  0.000000   

                              317712  ...     ZWINT      ZXDA      ZXDB  \
TCGA-4C-A93U-01A-11R-A39I-07     0.0  ...  7.612397  6.100828  7.989480   
TCGA-BJ-A0YZ-01A-11R-A10U-07     0.0  ...  6.704461  5.683576  8.029609   
TCGA-BJ-A0Z0-01A-11R-A10U-07     0.0  ...  7.315837  6.285243  8.870615   
TCGA-BJ-A0Z2-01A-11R-A10U-07     0.0  ...  8.804562  5.870093  8.659544   
TCGA-BJ-A0Z3-01A-11R-A13Y-07     0.0  ...  7.938185  6.006493  8.534474   
...                              ...  ...       ...       ...       ...   
TCGA-MK-A4N6-01A-11R-A250-07     0.0  ...  7.534200  5.225445  8.542219   
TCGA-MK-A4N7-01A-11R-A250-07     0.0  ...  6.821435  5.948554  8.686597   
TCGA-MK-A4N9-01A-11R-A250-07     0.0  ...  6.612963  5.736031  8.288401   
TCGA-MK-A84Z-01A-11R-A39I-07     0.0  ...  7.879401  5.910164  8.227827   
TCGA-QD-A8IV-01A-11R-A39I-07     0.0  ...  7.525871  6.288104  8.884408   

                                   ZXDC    ZYG11A     ZYG11B        ZYX  \
TCGA-4C-A93U-01A-11R-A39I-07   9.759390  4.759529  10.813808  12.115444   
TCGA-BJ-A0YZ-01A-11R-A10U-07   9.784443  5.880012   9.952747  11.124221   
TCGA-BJ-A0Z0-01A-11R-A10U-07  10.096284  6.728250  11.060050  10.090026   
TCGA-BJ-A0Z2-01A-11R-A10U-07  10.220458  6.267133  10.276796   9.565787   
TCGA-BJ-A0Z3-01A-11R-A13Y-07  10.033615  4.691797  10.668134  11.901242   
...                                 ...       ...        ...        ...   
TCGA-MK-A4N6-01A-11R-A250-07  10.028337  5.996825  11.457597  12.177864   
TCGA-MK-A4N7-01A-11R-A250-07  10.166190  4.043808  10.651912  11.481169   
TCGA-MK-A4N9-01A-11R-A250-07  10.334155  2.893401  10.409751  11.909396   
TCGA-MK-A84Z-01A-11R-A39I-07  10.060059  6.820788  10.353965  10.862017   
TCGA-QD-A8IV-01A-11R-A39I-07  10.403894  7.470326  10.551708  10.166781   

                                  ZZEF1       ZZZ3  class  
TCGA-4C-A93U-01A-11R-A39I-07   9.765008   9.358773      1  
TCGA-BJ-A0YZ-01A-11R-A10U-07  10.541867   9.568781      1  
TCGA-BJ-A0Z0-01A-11R-A10U-07  10.662298  10.375914      1  
TCGA-BJ-A0Z2-01A-11R-A10U-07  10.355813  10.218733      1  
TCGA-BJ-A0Z3-01A-11R-A13Y-07  10.218508   9.914348    